name: Database test

on:
  push:
    branches:
      - Team-BDD
      - Team-DW
      - Feat/pipelines
  pull_request:
    branches:
      - Team-BDD
      - Team-DW

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Wait for MySQL service to start
        run: sudo systemctl is-active mysql.service

      - name: Run database tests
        env:
          MYSQL_HOST: localhost
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: reeftest
        run: pytest tests/test_db.py --mysql-host=localhost --mysql-user=root --mysql-password=root --mysql-db=reeftest
